repos:
-   repo:  https://github.com/pre-commit/pre-commit-hooks
    rev: v1.1.1
    hooks:
    -   id: trailing-whitespace
-   repo:  https://github.com/pre-commit/mirrors-eslint
    rev: v4.10.0
    hooks:
    -   id: eslint
        args: [--fix]
        additional_dependencies:
        - eslint-config-google
        - eslint-loader
        - eslint-plugin-react
        - babel-eslint
